services:
  k-line:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/tokens"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - k-line-network

  # Optional: Add monitoring service
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - k-line-network

networks:
  k-line-network:
    driver: bridge 