# K-Line Data Service Production Configuration

[server]
host = "0.0.0.0"
port = 8080
workers = 16
max_connections = 50000
request_timeout = 60

[database]
url = "postgres://postgres:my_password@database:5432/k_line_db"
max_connections = 50
connection_timeout = 10

[logging]
level = "warn"
file_output = true
file_path = "/var/log/k-line/app.log"

[cache]
ttl = 600         # 10 minutes
max_items = 50000

[performance]
worker_threads = 16
websocket_heartbeat_interval = 5
client_timeout = 10
kline_retention_hours = 24
max_websocket_connections = 10000
channel_capacity = 5000
batch_size = 500

[data_generation]
interval_ms = 100
volatility = 0.02
volume_range = [100.0, 1000.0]
enabled = true
